# Generated by Django 5.0.7 on 2024-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_department_studentone'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sc_name', models.CharField(max_length=20)),
                ('desciption', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Studentmany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('contect', models.IntegerField()),
                ('dep_name', models.ManyToManyField(to='app.school')),
            ],
        ),
    ]
